#!/bin/sh

set -e

REPO_ROOT_DIR="$(git rev-parse --show-toplevel)"

# Spotless enforcer
echo "Running spotless"
./gradlew spotlessApply

# Find all files with changes and stage them
changed_files=$(git diff --cached --name-only --diff-filter=ACMR)

if [ -n "$changed_files" ]; then
    echo "Processing changed files..."
    git add $changed_files
else
    echo "No changes to process."
fi
