#!/bin/sh

set -e

REPO_ROOT_DIR="$(git rev-parse --show-toplevel)"

# Spotless enforcer
echo "Running spotless"
./gradlew spotlessApply

# Function to handle file additions
process_files() {
    local pattern=$1
    local files

    files=$(git diff --cached --name-only --diff-filter=ACMR | grep -Ei "$pattern" || true)
    if [ -n "$files" ]; then
        git add $files
    fi
}

# Process specific file types
process_files "\.gradle$"
process_files "\.java$"
process_files "\.kt$"
