#!/bin/sh

set -e

REPO_ROOT_DIR="$(git rev-parse --show-toplevel)"

#Spotless enforcer
echo "Running spotless"
./gradlew spotlessApply
files=$((git diff --cached --name-only --diff-filter=ACMR | grep -Ei "\.gradle$") || true)
if [ ! -z "${files}" ]; then
    comma_files=$(echo "$files" | paste -s -d "," -)
    git add $(echo "$files" | paste -s -d " " -)
fi
files=$((git diff --cached --name-only --diff-filter=ACMR | grep -Ei "\.java$") || true)
if [ ! -z "${files}" ]; then
    comma_files=$(echo "$files" | paste -s -d "," -)
    git add $(echo "$files" | paste -s -d " " -)
fi
files=$((git diff --cached --name-only --diff-filter=ACMR | grep -Ei "\.kotlin$") || true)
if [ ! -z "${files}" ]; then
    comma_files=$(echo "$files" | paste -s -d "," -)
    git add $(echo "$files" | paste -s -d " " -)
fi
